const config = require('@modusoperandi/eslint-config');
module.exports = [
  ...config.getFlatConfig({
    strict: false,
    header: config.header.mit,
  }),
  {
    rules: {
      'import/no-cycle': 'warn',
      'no-constant-binary-expression': 'warn',
      'import/no-named-as-default-member': 'warn',
      'import/no-named-as-default': 'warn',
      '@typescript-eslint/restrict-template-expressions': 'warn',
      '@typescript-eslint/no-unused-expressions': 'warn',
      '@typescript-eslint/no-base-to-string': 'warn',
      '@typescript-eslint/no-unsafe-return': 'warn',
      '@typescript-eslint/await-thenable': 'warn',
      '@typescript-eslint/require-await': 'warn',
      '@typescript-eslint/no-floating-promises': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-require-imports': 'warn',
      'sonarjs/slow-regex': 'warn',
      'sonarjs/array-callback-without-return': 'warn',
      'sonarjs/no-identical-functions': 'warn',
      'sonarjs/no-misleading-array-reverse': 'warn',
      'sonarjs/no-incomplete-assertions': 'warn',
      'sonarjs/updated-loop-counter': 'warn',
      'sonarjs/no-invariant-returns': 'warn',
      'sonarjs/public-static-readonly': 'warn',
      'sonarjs/no-nested-functions': 'warn',
      'sonarjs/cognitive-complexity': 'warn',
      'sonarjs/prefer-single-boolean-return': 'warn',
      'sonarjs/prefer-read-only-props': 'warn',
      'sonarjs/prefer-regexp-exec': 'warn',
      'sonarjs/constructor-for-side-effects': 'warn',
      'sonarjs/no-dead-store': 'warn',
      'sonarjs/no-undefined-argument': 'warn',
    },
  },
  {
    files: ['**/*.test.ts', '**/*.test.tsx'],
    rules: {
      'jest/valid-expect': 'warn',
      'jest/no-done-callback': 'warn',
      'jest/expect-expect': 'warn',
      'jest/no-identical-title': 'warn',
      'jest/no-conditional-expect': 'warn',
      'jest/require-top-level-describe': 'warn',
    },
  },
];
